version: '3'

services:
  python:
    depends_on: [keycloak]
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-keycloak-python"
    image: "${EDS_IMAGE_PREFIX:-eds}-keycloak-python"
    build:
      context: "./docker-python"
    volumes:
      - ./keycloak/realm_setup.py:/app/realm_setup.py
      - ./keycloak/python_setup_data/:/app/data/
    environment:
      - KEYCLOAK_ADMIN_PASSWORD
      - KEYCLOAK_ADMIN
      - KEYCLOAK_GITLAB_SECRET
      - KEYCLOAK_JUPYTER_SECRET
      - KEYCLOAK_MATRIX_SECRET
      - EDS_DOMAIN
      - EDS_CONTAINER_PREFIX
    command: ['realm_setup.py']
    networks:
      - "${EDS_CONTAINER_PREFIX:-eds}-network"
      - keycloak_network

