version: '3'

services:
  nginx:
    depends_on:
      - jupyterhub
  jupyterhub:
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-jupyterhub"
    image: "${EDS_IMAGE_PREFIX:-eds}-jupyterhub"
    build:
      context: "./jupyterhub"

    volumes:
      - ./jupyterhub/data:/srv/jupyterhub  # Custom configuration directory
      - /var/run/docker.sock:/var/run/docker.sock # For DockerSpawner
      
    environment:
      JUPYTERHUB_JUPYTER_IMAGE_NAME: "$JUPYTERHUB_JUPYTER_IMAGE_NAME"
      OAUTH2_AUTHORIZE_URL: "https://keycloak.$EDS_DOMAIN/realms/royaume/protocol/openid-connect/auth"
      OAUTH2_REALM_URL:     "https://keycloak.$EDS_DOMAIN/realms/royaume"
      
      OAUTH2_TOKEN_URL:     "https://eds-keycloak:8443/realms/royaume/protocol/openid-connect/token"
      OAUTH2_USERDATA_URL:  "https://eds-keycloak:8443/realms/royaume/protocol/openid-connect/userinfo"
      
      OAUTH2_CLIENT_ID: "jupyterhub"
      OAUTH2_CLIENT_SECRET: "$KEYCLOAK_JUPYTER_SECRET"
      OAUTH_CALLBACK_URL:   "https://jupyter.$EDS_DOMAIN/hub/oauth_callback"
      
      JUPYTERHUB_API_URL: "https://eds-jupyterhub/hub/api"
    command: jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
    networks:
      - "${EDS_CONTAINER_PREFIX:-eds}-network"
