services:
  python:
    depends_on: [keycloak]
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-keycloak-python"
    image: "${EDS_IMAGE_PREFIX:-eds}-keycloak-python"
    build:
      context: "./docker-python"
    volumes:
      - ./keycloak/realm_setup.py:/app/realm_setup.py
      - ./config/keycloak/:/app/data/:ro
    environment:
      - KEYCLOAK_ADMIN_PASSWORD
      - KEYCLOAK_ADMIN
      # - KEYCLOAK_GITLAB_SECRET
      # - KEYCLOAK_JUPYTER_SECRET
      # - KEYCLOAK_MATRIX_SECRET
      - KEYCLOAK_CLIENT_SECRET
      - EDS_DOMAIN
      - EDS_CONTAINER_PREFIX
    entrypoint: ['python', './realm_setup.py']
    # entrypoint: ['sleep', '600']
    networks:
      - eds_network

