version: '3'

services:
  matrix-postgres:
    image: docker.io/postgres:latest
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-matrix-postgres"
    environment:
      - POSTGRES_DB=matrix
      - POSTGRES_USER=matrix
      - POSTGRES_PASSWORD=$MATRIX_POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./matrix/postgres/volume/:/var/lib/postgresql/data
    networks:
      - matrix_network
    restart: always
    
  matrix:
    depends_on:
      - matrix-postgres
      - keycloak
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-matrix"
    image: "${EDS_IMAGE_PREFIX:-eds}-matrix"
    build:
      context: "./matrix/matrix"
    environment:
      - SYNAPSE_SERVER_NAME=${EDS_IMAGE_PREFIX:-eds}-matrix
      - SYNAPSE_REPORT_STATS=no
    volumes:
      - ./matrix/matrix/data/:/data
    networks:
      - matrix_network
      - eds_network
    entrypoint: ["/start.sh"]
    # entrypoint: ["sleep", "600"]

  matrix-element-web:
    depends_on: [matrix]
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-matrix-element"
    image: "${EDS_IMAGE_PREFIX:-eds}-matrix-element"
    build:
      context: "./matrix/element"
    volumes:
      - ./matrix/element/element-config.json:/app/config.json
    networks:
      - matrix_network
      - eds_network

networks:
  matrix_network:
