version: '3.8' 

services:
  nginx:
    image: nginx:alpine
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificates/privkey.pem:/etc/ssl/private/nginx.key:ro
      - ./nginx/certificates/fullchain.pem:/etc/ssl/certs/nginx.crt:ro
      - ./website/frontend/app/dist/:/usr/share/nginx/html/:ro
    ports:
      - "8888:443"
    networks:
      eds_network:
      eds_outside_world:
        ipv4_address: 172.16.202.8
        priority: 9000
    command: /bin/sh -c "sleep 5 && nginx -g 'daemon off;'"
