version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-nginx"
    depends_on:
      - keycloak
      - matrix
      - jupyterhub
      - gitlab
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificates/privkey.pem:/etc/ssl/private/nginx.key:ro
      - ./nginx/certificates/fullchain.pem:/etc/ssl/certs/nginx.crt:ro
    ports:
      - "8888:443"
    networks:
      - eds_network
    command: /bin/sh -c "sleep 5 && nginx -g 'daemon off;'"
