version: '3'

services:
  matrix-postgres:
    image: docker.io/postgres:latest
    image: 'eds-matrix-postgres'
    container_name: "eds-matrix-postgres"
    environment:
      - POSTGRES_DB=matrix
      - POSTGRES_USER=matrix
      - POSTGRES_PASSWORD=$MATRIX_POSTGRES_PASSWORD
      # ensure the database gets created correctly
      # https://matrix-org.github.io/synapse/latest/postgres.html#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./matrix/postgres/volume/:/var/lib/postgresql/data
    networks:
      - matrix_network
    restart: always
    
  matrix:
    depends_on: [matrix-postgres, keycloak]
    container_name: "eds-matrix"
    image: eds-matrix
    build:
      context: "./matrix/matrix"
    environment:
      - SYNAPSE_SERVER_NAME=eds-matrix
      - SYNAPSE_REPORT_STATS=no
    volumes:
      - ./matrix/matrix/data/:/data
    networks:
      - matrix_network
      - eds_network
    entrypoint: ["/start.sh"]

  matrix-element-web:
    depends_on: [matrix]
    container_name: "eds-matrix-element"
    image: eds-matrix-element
    build:
      context: "./matrix/element"
    volumes:
      - ./matrix/element/element-config.json:/app/config.json
    networks:
      - eds_network
      - matrix_network

networks:
  matrix_network:
