version: '3.8' 

services:
  jupyterhub:
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-jupyterhub"
    image: "${EDS_IMAGE_PREFIX:-eds}-jupyterhub"
    build:
      context: "./jupyterhub"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # For DockerSpawner
      # config
      - ./config/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      # data
      - ./data/jupyterhub/data:/srv/jupyterhub 
      
    environment:
      JUPYTERHUB_JUPYTER_IMAGE_NAME: "$JUPYTERHUB_JUPYTER_IMAGE_NAME"
      OAUTH2_AUTHORIZE_URL: "https://keycloak.$EDS_DOMAIN/realms/royaume/protocol/openid-connect/auth"
      OAUTH2_REALM_URL:     "https://keycloak.$EDS_DOMAIN/realms/royaume"
      
      OAUTH2_TOKEN_URL:     "https://${EDS_CONTAINER_PREFIX}-keycloak:8443/realms/royaume/protocol/openid-connect/token"
      OAUTH2_USERDATA_URL:  "https://${EDS_CONTAINER_PREFIX}-keycloak:8443/realms/royaume/protocol/openid-connect/userinfo"
      
      OAUTH2_CLIENT_ID: "jupyterhub"
      OAUTH2_CLIENT_SECRET: "$KEYCLOAK_JUPYTER_SECRET"
      OAUTH_CALLBACK_URL:   "https://jupyter.$EDS_DOMAIN/hub/oauth_callback"
      
      JUPYTERHUB_API_URL: "https://${EDS_CONTAINER_PREFIX}-jupyterhub/hub/api"
    command: jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
    networks:
      - eds_network
      
