version: '3'

services:
  keycloak-db:
    image: postgres
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-keycloak-postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: $KEYCLOAK_POSTGRES_PASSWORD
      # POSTGRES_USER: $KEYCLOAK_POSTGRES_USER
      POSTGRES_USER: postgres
    volumes:
      - ./keycloak/postgres/volume/data:/var/lib/postgresql/data
    networks:
      - keycloak_network
  
  keycloak-adminer:
    image: adminer
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-keycloak-adminer"
    restart: always
    # ports:
    #   - 7611:8080
    networks:
      - keycloak_network

  keycloak:
    depends_on: [keycloak-db]
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-keycloak"
    image: "${EDS_IMAGE_PREFIX:-eds}keycloak"
    build:
      context: "./keycloak"
    environment:
      - KEYCLOAK_ADMIN=$KEYCLOAK_ADMIN
      - KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
      - KEYCLOAK_PROXY_ADDRESS_FORWARDING=true
      - KC_HTTP_ENABLED=true
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=$KEYCLOAK_POSTGRES_PASSWORD
    command:
      - start-dev
      # - start
      # https://www.keycloak.org/server/reverseproxy
      - --proxy=edge
      - --hostname-strict=false
      - --hostname-strict-https=false
      - --hostname=keycloak.$EDS_DOMAIN
      - --db-url=jdbc:postgresql://${EDS_CONTAINER_PREFIX:-eds}-keycloak-postgres/postgres
      - --hostname-debug=true
      - --hostname-admin-url=https://keycloak.$EDS_DOMAIN
      - --log-level=WARN # debug | TRACE | ALL | WARN
      - --db=postgres
      # - --db-username=keycloak
      - --db-password=$KEYCLOAK_POSTGRES_PASSWORD
    networks:
      eds_network:
      keycloak_network:
        priority: 88

networks:
  keycloak_network:
    
