version: '3'

services:
  centos:
    image: centos:centos7
    container_name: "${EDS_CONTAINER_PREFIX:-eds}-centos"
    volumes:
      - ./centos/data/:/root/
    networks:
      - eds_network
      - eds_outside_world
    command: sleep 9999


