#!/bin/bash

set -eu

echo "creating secret key for '$1'"
if ! grep -q "$1=" "$2"; then
    p="$(./lib/randompass 64 'a-zA-Z0-9_')"
    echo "export $1='$p'" >> "$2"
else
    echo "$1 already exists."
fi
