#!/bin/bash

set -eu

echo "creating secret key for '$1'"
touch "$2"

if ! grep -Eq "$1=.*[[:alnum:]].*" "$2"; then
    p="$(./lib/randompass 64 'a-zA-Z0-9_')"
    if grep -q "$1=" "$2" ; then
        sed -i "s/.*$1=.*/export $1='$p'/" "$2"
    else
        echo "export $1='$p'" >> "$2"
    fi
else
    echo "$1 already exists."
fi
